# Generated by Django 5.0 on 2024-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_end_date_member_start_date_student_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('work_expirence', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
