# Generated by Django 5.0 on 2024-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
