# Generated by Django 5.0 on 2024-01-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_portfolio_end_date_alter_portfolio_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Portfolios',
        ),
    ]
