# Generated by Django 5.0 on 2024-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_portfolio_portfolios'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('work_expirence', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolios',
        ),
    ]
