# Generated by Django 5.0 on 2024-01-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_user_port_delete_portfolios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_port',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
