# Generated by Django 5.0 on 2024-01-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_user_port_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_port',
            name='contact',
            field=models.IntegerField(default=18),
        ),
    ]
