# Generated by Django 5.0 on 2024-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_user_port_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_port',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
